<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Enable XML Documentation -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <!-- Suppress warnings for missing XML comments -->
    <NoWarn>1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Microsoft.OpenApi" Version="1.6.14" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FoodOrdering.Common\FoodOrdering.Common.csproj" />
    <ProjectReference Include="..\FoodOrdering.Data\FoodOrdering.Data.csproj" />
    <ProjectReference Include="..\FoodOrdering.Service\FoodOrdering.Service.csproj" />
    <ProjectReference Include="..\FoodOrdering.Store\FoodOrdering.Store.csproj" />
  </ItemGroup>

</Project>