<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\FoodOrdering.Common\FoodOrdering.Common.csproj" />
		<ProjectReference Include="..\FoodOrdering.Data\FoodOrdering.Data.csproj" />
		<ProjectReference Include="..\FoodOrdering.Store\FoodOrdering.Store.csproj" />
	</ItemGroup>

</Project>
